# ================================
# USERS HTTP TESTS
# ================================

# CREATE USER
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "nome": "Juca Bala",
  "email": "juca@bala.com",
  "senha": "12345",
  "telefone": "555",
}